export enum SORT_DROPDOWN {
  POPULAR_ASCENDING = "POPULAR_ASCENDING",
  POPULAR_DESCENDING = "POPULAR_DESCENDING",
  RELEASE_DATE_ASCENDING = "RELEASE_DATE_ASCENDING",
  RELEASE_DATE_DESCENDING = "RELEASE_DATE_DESCENDING",
  RATING_ASCENDING = "RATING_ASCENDING",
  RATING_DESCENDING = "RATING_DESCENDING",
}

export enum VIEW_BY {
  POPULARITY = "popular",
  RELEASE_DATE = "release_date",
}
